### ISSUE TITLE
WordPress Theme

### ISSUE THREAD

**Issue by hone-zaun** [sajidali007522/edu-website#1]
Hi @sajidali007522 !

Just recently I found out about the work on https://eduhpversiontwo.wpdeveloper.at/

1. This is not quite what I was expecting to see.
    * Why did you use/overwrite/change the ORIGINAL 2020-WP-THEME???
      * This is something no one should do! NEVER EVER!
      * DO NOT CHANGE A WORKING THEME WHICH IS NOT FROM YOU!!!!
    * You should place your code either in a **child theme**
      * https://developer.wordpress.org/themes/advanced-topics/child-themes/
    * or make a **new theme**
      * maybe based on https://underscores.me/
    * **Please change it!**
2. Please use this repository for the code on the WP-Theme
3. You do not need to think about translating the post entries. We're going to do that on our own.
4. What did work as expected:
    * **It's all about the blog**.
    * So we only need the blog design.

**Comment by sajidali007522** [comment]
@hone-zaun  Done with all above points.

**Comment by hone-zaun** [comment]
Thank you
