### ISSUE TITLE
Your Code is messy.

### ISSUE THREAD

**Issue by hone-zaun** [sajidali007522/edu-website#2]
https://eduhpversiontwo.wpdeveloper.at/

* ![grafik](https://user-images.githubusercontent.com/51439140/83517497-4292d900-a4d9-11ea-8638-37be615c04ab.png)
* It is not good and also not necessary to use a variable for HTML **and** PHP at the same time you echo it. Please use plain HTML in such cases and fill the proper PHP stuff like this:
  * ![grafik](https://user-images.githubusercontent.com/51439140/83517846-e4b2c100-a4d9-11ea-8e62-a4242b549883.png)
* Do not mix translation function domains!
  * ![grafik](https://user-images.githubusercontent.com/51439140/83518633-f779c580-a4da-11ea-8b76-dedf5921dc1b.png)
* And also use the correct domains for translation functions!
  * ![grafik](https://user-images.githubusercontent.com/51439140/83519116-c0f07a80-a4db-11ea-8187-d72cd1798f6b.png)
* Please refactor your code style. Especially the indentations are messy and therefore it's not as easy to read our code as it should be!
  * ![grafik](https://user-images.githubusercontent.com/51439140/83518915-5c352000-a4db-11ea-8baa-689f677282d3.png)
* refactor header.php
  * This should become a WordPress-Theme. So use the WordPress functions to load stylesheets and JS as well as menus, logos and Images!
      * ![grafik](https://user-images.githubusercontent.com/51439140/83519421-38260e80-a4dc-11ea-8f9e-070c41fbeca9.png)
  * Use **template-parts** for blocks like this and refactor code style and indentations to make it more readable:
      * ![grafik](https://user-images.githubusercontent.com/51439140/83519795-e336c800-a4dc-11ea-94c0-3cdee5d2c589.png)

**Comment by sajidali007522** [comment]
@hone-zaun  Done with all above points

**Comment by hone-zaun** [comment]
@sajidali007522 

## singular.php

1. There are still some strange constructs in the code.
    * But maybe you can explain me this part of your code. Just in case I don't get the importance of wrapping an anchor with another anchor...
    * ![grafik](https://user-images.githubusercontent.com/51439140/84660493-39622d00-af19-11ea-8e77-ebf4d18ee2ce.png)
2. There is absolutely no reason to use `get_the_post_thumbnail_url( get_the_ID(), 'full' )` here.
    * We are in the WP-Loop, so we do not need to worry about the post_id
    * With your code we don't get the `srcset`- and `sizes`-attribute which is kinda useful for mobile browsers.
    * Also WordPress takes care about the `alt`-attribute if set correctly by the user in the Backend
3. ## It is never a good Idea to use a post_id this way.
    * ![grafik](https://user-images.githubusercontent.com/51439140/84681134-ffeaeb00-af33-11ea-926d-1350b5d5199f.png)
    * Of course we can easily figure it out which page this is. It is the blog-page!
      * https://eduhpversiontwo.wpdeveloper.at/wp-admin/post.php?post=7&action=edit
    * BUT: If we want to use the Theme somewhere else, where the blog-page has a different ID, what will happen to your code???
4. You set up an **options page** for the theme. Which is ok. The customizer would have been another option for that. But we can keep it this way!
    * https://eduhpversiontwo.wpdeveloper.at/wp-admin/admin.php?page=theme-general-settings
      * ![grafik](https://user-images.githubusercontent.com/51439140/84681258-26a92180-af34-11ea-9c22-eb1a2429cd2d.png)
    * ## BUT: In this case you should put all these ACFs in this first option page!
      * https://eduhpversiontwo.wpdeveloper.at/wp-admin/admin.php?page=theme-general-settings
      * https://eduhpversiontwo.wpdeveloper.at/wp-admin/post.php?post=174&action=edit
      * ![grafik](https://user-images.githubusercontent.com/51439140/84685493-b05bed80-af3a-11ea-9bd4-bb3d09e38730.png)
  * ## Ok, i didn't realize the other two ACFs (blog_title and tagline) are also used in the singular.php. So this task is even easier because we don't need to split it, just change the location and it's post_id in the code

**Comment by sajidali007522** [comment]
@hone-zaun  done with all above points 
some small points, sometime need to create small structure for make it according to design. 
but now its done.

**Comment by hone-zaun** [comment]
@sajidali007522 Thank you!
