### ISSUE TITLE
Please put all these hardcoded Strings into a translation function

### ISSUE THREAD

**Issue by hone-zaun** [sajidali007522/edu-website#3]
https://eduhpversiontwo.wpdeveloper.at/depression-burnout/

* ![grafik](https://user-images.githubusercontent.com/51439140/83520279-ba630280-a4dd-11ea-82f1-4e96732a60d5.png)
* ![grafik](https://user-images.githubusercontent.com/51439140/83520343-d6ff3a80-a4dd-11ea-810f-198503a2cb62.png)
* **_e( 'some string', 'edupression_hp' );**
* **__( 'some string', 'edupression_hp' );**
  * https://developer.wordpress.org/reference/functions/_e/
  * https://codex.wordpress.org/I18n_for_WordPress_Developers

**Comment by sajidali007522** [comment]
@hone-zaun  I done all of above points please check it. 
- Created new theme 
- Everything now editable please check it and let me know about it.

**Comment by hone-zaun** [comment]
Thank you
